server {
    listen 127.0.0.1:8080;
    root ./www;
    index index.html;

    location / {
        methods GET;
    }

    location /images {
        methods GET;
        root ./www/images;
    }

    location /images/icons {
        methods GET;
        root ./www/icons;
    }
}

server {
    listen 127.0.0.1:8081;
    root ./www/site_b;
    index index.html;

    location / {
        methods GET;
    }
}
