server {
    listen 127.0.0.1:8080;
    root ./www;
    index index.html;

    error_page 404 /errors/404.html;

    location / {
        methods GET;
        autoindex off;
    }

    location /listing {
        methods GET;
        autoindex on;
    }

    location /private-directory {
        methods GET;
        autoindex off;
    }

    location /has-index {
        methods GET;
        index home.html index.html;
        autoindex on;
    }
}
