server {
    listen 127.0.0.1:8080;
    root ./www;
    index index.html;
    client_max_body_size 10M;

    error_page 400 /errors/400.html;
    error_page 404 /errors/404.html;
    error_page 413 /errors/413.html;

    location / {
        methods GET;
        autoindex off;
    }

    location /old {
        methods GET;
        return 301 /;
    }

    location /post-only {
        methods POST;
    }

    location /listing {
        methods GET;
        autoindex on;
    }

    location /private-directory {
        methods GET;
        autoindex off;
    }

    location /has-index {
        methods GET;
        index home.html index.html;
        autoindex on;
    }

    location /echo {
        methods POST;
        client_max_body_size 11;
    }

    location /upload {
        methods GET POST;
        upload on;
        upload_store ./www/uploads;
        client_max_body_size 1M;
    }

    location /delete {
        methods DELETE;
        root ./www/uploads;
    }

    location /cgi-bin {
        methods GET POST;
        root ./www/cgi-bin;
        cgi .py /usr/bin/python3;
        client_max_body_size 1M;
    }
}

server {
    listen 127.0.0.1:8081;
    root ./www/site_b;
    index index.html;

    location / {
        methods GET;
        autoindex off;
    }
}
