server {
    listen 127.0.0.1:8080;
    root ./www;
    index index.html;
    client_max_body_size 128M;

    location / {
        methods GET;
        autoindex off;
    }

    location /post_body {
        methods POST;
        client_max_body_size 100;
    }

    location /directory {
        methods GET POST;
        root ./YoupiBanane;
        index youpi.bad_extension;
        autoindex on;
        cgi .bla ./cgi_tester;
    }

    location /directory/Yeah {
        methods GET;
        root ./YoupiBanane/missing-Yeah-directory;
    }

    location /directory/Yeah/not_happy.bad_extension {
        methods GET;
        root ./YoupiBanane/Yeah/not_happy.bad_extension;
    }
}
